#!/usr/bin/env bash
# Performs various tasks:
#   - Creates /var/run/holbertonscript.pid with script PID.
#   - Displays messages indefinitely.
#   - Responds to SIGTERM with a message and cleanup.
#   - Responds to SIGINT with a message.
#   - Deletes /var/run/holbertonscript.pid and exits on SIGQUIT/SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
