#!/usr/bin/env bash
# Displays specific information from the `/etc/passwd` file.
#  Only prints the username, user ID, and user home directory path.

while read passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
