#!/usr/bin/env bash
# Utilizes a while loop to output "Best School" 10 times.
# On the 9th iteration, it displays "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
