#!/usr/bin/env bash
# Configures an Ubuntu server by modifying the /etc/hosts file:
#   - Sets localhost to resolve to 127.0.0.2
#   - Sets facebook.com to resolve to 8.8.8.8

# Create a backup of the current /etc/hosts file.
cp /etc/hosts ~/hosts.new

# Add new entries for localhost and facebook.com to the ~/hosts.new file.
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Overwrite the original /etc/hosts file with the updated one.
cp -f ~/hosts.new /etc/hosts
